config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :schedules
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :buses
  resources :drivers
  resources :passengers
  resources :routes
  resources :tickets
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    validates_presence_of :name, :contact, :address, :age, :gender
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_passenger, only: [:show, :edit, :update, :destroy]
  # GET /passengers or /passengers.json
  def index
    @passengers = Passenger.all
  end

  # GET /passengers/1 or /passengers/1.json
  def show
  end

  # GET /passengers/new
  def new
    @passenger = Passenger.new
  end

  # GET /passengers/1/edit
  def edit
  end

  # POST /passengers or /passengers.json
  def create
    @passenger = Passenger.new(passenger_params)

    respond_to do |format|
      if @passenger.save
        format.html { redirect_to passenger_url(@passenger), notice: "Passenger was successfully created." }
        format.json { render :show, status: :created, location: @passenger }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passengers/1 or /passengers/1.json
  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to passenger_url(@passenger), notice: "Passenger was successfully updated." }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passengers/1 or /passengers/1.json
  def destroy
    @passenger.destroy

    respond_to do |format|
      format.html { redirect_to passengers_url, notice: "Passenger was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def passenger_params
      params.require(:passenger).permit(:name, :contact, :address, :age, :gender)
    end
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/passengers/_form.html.erb
<%= form_with(model: passenger) do |form| %>
<% if passenger.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(passenger.errors.count, "error") %> prohibited this passenger from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% passenger.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :name, class: label_class %>
          <%= form.text_field :name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :contact, class: label_class %>
          <%= form.text_field :contact, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :address, class: label_class %>
          <%= form.text_field :address, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :age, class: label_class %>
          <%= form.number_field :age, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :gender, class: label_class %>
          <%= form.text_field :gender, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if passenger.persisted? %>
<%= link_to "Cancel", passenger, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", passengers_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/passengers/_passenger.html.erb
<div id="<%= dom_id passenger %>">
  <p>
    <strong>Name:</strong>
    <%= passenger.name %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= passenger.contact %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= passenger.address %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= passenger.age %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= passenger.gender %>
  </p>

</div>

app/views/passengers/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit passenger</h1>
    <% if @passenger.persisted? %>
    <%= button_to 'Destroy', @passenger, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', passenger: @passenger %>
</div>

app/views/passengers/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Passengers</h1>

    <%= link_to new_passenger_path, class: button_class(theme: "primary") do %>
    Add New Passenger
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Name</th>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Contact</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Address</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Age</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Gender</th>
                
      </tr>
    </thead>

    <tbody>
      <% @passengers.each do |passenger| %>
      <%= content_tag :tr, id: dom_id(passenger), class: dom_class(passenger) do %>
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to passenger.name, passenger %></td>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= passenger.contact %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= passenger.address %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= passenger.age %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= passenger.gender %></td>
      
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/passengers/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New passenger</h1>

  <%= render 'form', passenger: @passenger %>
</div>

app/views/passengers/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Passenger</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to passengers_path, class: button_class(theme: "transparent") do %>
      All Passengers
      <% end %>
      <% if user_signed_in? %>
        <%= link_to 'Edit Passenger', edit_passenger_path(@passenger) %>
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Name:</p>
        <p><%= @passenger.name %></p>
      </li>
      <li>
        <p class="font-semibold">Contact:</p>
        <p><%= @passenger.contact %></p>
      </li>
      <li>
        <p class="font-semibold">Address:</p>
        <p><%= @passenger.address %></p>
      </li>
      <li>
        <p class="font-semibold">Age:</p>
        <p><%= @passenger.age %></p>
      </li>
      <li>
        <p class="font-semibold">Gender:</p>
        <p><%= @passenger.gender %></p>
      </li>
  </ul>
</div>