config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :schedules
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :buses
  resources :drivers
  resources :passengers
  resources :routes
  resources :tickets
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/driver.rb
class Driver < ApplicationRecord
    validates_presence_of :name, :phone_number, :address, :gender, :date_of_birth, :nationality
    validates_uniqueness_of :phone_number

    validate :date_of_birth_cannot_be_in_the_future
    def date_of_birth_cannot_be_in_the_future
        errors.add(:date_of_birth,"can't be in the future") if date_of_birth.present? && date_of_birth > Date.current
    end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers or /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1 or /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers or /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to driver_url(@driver), notice: "Driver was successfully created." }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1 or /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to driver_url(@driver), notice: "Driver was successfully updated." }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1 or /drivers/1.json
  def destroy
    @driver.destroy

    respond_to do |format|
      format.html { redirect_to drivers_url, notice: "Driver was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def driver_params
      params.require(:driver).permit(:name, :phone_number, :address, :gender, :date_of_birth, :nationality)
    end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_driver.html.erb
<div id="<%= dom_id driver %>">
  <p>
    <strong>Name:</strong>
    <%= driver.name %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= driver.phone_number %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= driver.address %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= driver.gender %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= driver.date_of_birth %>
  </p>

  <p>
    <strong>Nationality:</strong>
    <%= driver.nationality %>
  </p>

</div>

app/views/drivers/_form.html.erb
<%= form_with(model: driver) do |form| %>
<% if driver.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% driver.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :name, class: label_class %>
          <%= form.text_field :name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :phone_number, class: label_class %>
          <%= form.text_field :phone_number, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :address, class: label_class %>
          <%= form.text_field :address, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :gender, class: label_class %>
          <%= form.select :gender,[['Female','female'], ['Male','male']], {}, class:'form-control' %>
      </div>
  <div class="mb-6">
        <%= form.label :date_of_birth, class: label_class %>
          <%= form.date_field :date_of_birth, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :nationality, class: label_class %>
          <%= form.text_field :nationality, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if driver.persisted? %>
<%= link_to "Cancel", driver, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", drivers_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/drivers/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit driver</h1>
    <% if @driver.persisted? %>
    <%= button_to 'Destroy', @driver, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', driver: @driver %>
</div>

app/views/drivers/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Drivers</h1>

    <%= link_to new_driver_path, class: button_class(theme: "primary") do %>
    Add New Driver
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Name</th>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Phone number</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Address</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Gender</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Date of birth</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Nationality</th>
                
      </tr>
    </thead>

    <tbody>
      <% @drivers.each do |driver| %>
      <%= content_tag :tr, id: dom_id(driver), class: dom_class(driver) do %>
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to driver.name, driver %></td>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= driver.phone_number %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= driver.address %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= driver.gender %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= driver.date_of_birth %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= driver.nationality %></td>
      
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/drivers/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New driver</h1>

  <%= render 'form', driver: @driver %>
</div>

app/views/drivers/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Driver</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to drivers_path, class: button_class(theme: "transparent") do %>
        All Drivers
      <% end %>

      <% if user_signed_in? %>
        <%= link_to 'Edit Driver', edit_driver_path(@driver) %>
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
    <li>
      <p class="font-semibold">Name:</p>
      <p><%= @driver.name %></p>
      </li>
      <li>
        <p class="font-semibold">Phone number:</p>
        <p><%= @driver.phone_number %></p>
      </li>
      <li>
        <p class="font-semibold">Address:</p>
        <p><%= @driver.address %></p>
      </li>
      <li>
        <p class="font-semibold">Gender:</p>
        <p><%= @driver.gender %></p>
      </li>
      <li>
        <p class="font-semibold">Date of birth:</p>
        <p><%= @driver.date_of_birth %></p>
      </li>
      <li>
        <p class="font-semibold">Nationality:</p>
        <p><%= @driver.nationality %></p>
      </li>
  </ul>
</div>