config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :schedules
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :buses
  resources :drivers
  resources :passengers
  resources :routes
  resources :tickets
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_bus, only: [:show, :edit, :update, :destroy]

  # GET /buses or /buses.json
  def index
    @buses = Bus.all
  end

  # GET /buses/1 or /buses/1.json
  def show
  end

  # GET /buses/new
  def new
    @bus = Bus.new
  end

  # GET /buses/1/edit
  def edit
  end

  # POST /buses or /buses.json
  def create
    @bus = Bus.new(bus_params)

    respond_to do |format|
      if @bus.save
        format.html { redirect_to bus_url(@bus), notice: "Bus was successfully created." }
        format.json { render :show, status: :created, location: @bus }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buses/1 or /buses/1.json
  def update
    respond_to do |format|
      if @bus.update(bus_params)
        format.html { redirect_to bus_url(@bus), notice: "Bus was successfully updated." }
        format.json { render :show, status: :ok, location: @bus }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buses/1 or /buses/1.json
  def destroy
    @bus.destroy

    respond_to do |format|
      format.html { redirect_to buses_url, notice: "Bus was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus
      @bus = Bus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bus_params
      params.require(:bus).permit(:bus_number, :driver_id, :license_number, :chasissis_number, :model, :capacity, :year)
    end
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/views/buses/_bus.html.erb
<div id="<%= dom_id bus %>">
  <p>
    <strong>Bus number:</strong>
    <%= bus.bus_number %>
  </p>

  <p>
    <strong>Driver:</strong>
    <%= bus.driver_id %>
  </p>

  <p>
    <strong>License number:</strong>
    <%= bus.license_number %>
  </p>

  <p>
    <strong>Chasissis number:</strong>
    <%= bus.chasissis_number %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= bus.model %>
  </p>

  <p>
    <strong>Capacity:</strong>
    <%= bus.capacity %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= bus.year %>
  </p>

</div>

app/views/buses/_form.html.erb
<%= form_with(model: bus) do |form| %>
<% if bus.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(bus.errors.count, "error") %> prohibited this bus from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% bus.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :bus_number, class: label_class %>
          <%= form.number_field :bus_number, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :driver_id, class: label_class %>
          <%= form.collection_select :driver_id, Driver.all, :id, :name, { promt:true }, id: 'driver-select' %>
      </div>
  <div class="mb-6">
        <%= form.label :license_number, class: label_class %>
          <%= form.number_field :license_number, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :chasissis_number, class: label_class %>
          <%= form.text_field :chasissis_number, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :model, class: label_class %>
          <%= form.text_field :model, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :capacity, class: label_class %>
          <%= form.select :capacity, [['30 people','30 people'], ['50 people','50 people']], {}, class:'form-control' %>
      </div>
  <div class="mb-6">
        <%= form.label :year, class: label_class %>
          <%= form.date_field :year, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if bus.persisted? %>
<%= link_to "Cancel", bus, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", buses_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/buses/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit bus</h1>
    <% if @bus.persisted? %>
    <%= button_to 'Destroy', @bus, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', bus: @bus %>
</div>

app/views/buses/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Buses</h1>

    <%= link_to new_bus_path, class: button_class(theme: "primary") do %>
    Add New Bus
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Bus number</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Driver</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">License number</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Chasissis number</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Model</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Capacity</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Year</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @buses.each do |bus| %>
      <%= content_tag :tr, id: dom_id(bus), class: dom_class(bus) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= bus.bus_number %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= bus.driver.name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= bus.license_number %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= bus.chasissis_number %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= bus.model %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= bus.capacity %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= bus.year %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', bus %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/buses/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New bus</h1>

  <%= render 'form', bus: @bus %>
</div>

app/views/buses/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Bus</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to buses_path, class: button_class(theme: "transparent") do %>
      All Buses
      <% end %>
      <% if user_signed_in? %>
        <%= link_to 'Edit Bus', edit_bus_path(@bus) %>
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Bus number:</p>
        <p><%= @bus.bus_number %></p>
      </li>
      <li>
        <p class="font-semibold">Driver:</p>
        <p><%= @bus.driver.name %></p>
      </li>
      <li>
        <p class="font-semibold">License number:</p>
        <p><%= @bus.license_number %></p>
      </li>
      <li>
        <p class="font-semibold">Chasissis number:</p>
        <p><%= @bus.chasissis_number %></p>
      </li>
      <li>
        <p class="font-semibold">Model:</p>
        <p><%= @bus.model %></p>
      </li>
      <li>
        <p class="font-semibold">Capacity:</p>
        <p><%= @bus.capacity %></p>
      </li>
      <li>
        <p class="font-semibold">Year:</p>
        <p><%= @bus.year %></p>
      </li>
  </ul>
</div>